### ISSUE TITLE
Is there any plan for "crypto_vue-native"

### ISSUE THREAD

**Issue by manualsh** [djirdehh/crypto_vue#14]
Hi Hassan @djirdehh Browsing through vuejs repo came across weex library for vue-native. So is there a possibility for crypto_vue-native? https://github.com/vuejs/vue/issues/2119

"Weex: A framework for building Native Mobile cross-platform UI"
http://alibaba.github.io/weex/ based on vuejs.
https://weex.incubator.apache.org/

**Comment by djirdehh** [comment]
Just saw this, apologize for the late response!

Hm that's a solid idea but I don't think I'll be moving towards to making it a native app. CryptoVue is mobile responsive and has a manifest file to allow users to install it webpage to their home screen, whic I hope suffices now?
