### ISSUE TITLE
No logo for Cardano & Bitcoin Gold

### ISSUE THREAD

**Issue by maxenceC** [djirdehh/crypto_vue#17]
Hey, 

It's just a detail, but there's no Logo for Cardano & Bitcoin Gold.

I guess they were not in the top 10 when you built the website.

Nice work tho !

**Comment by djirdehh** [comment]
Yup will be addressing this soon. The downside of setting up all data on the front-end and the volatility of crypto 😄 .

**Comment by maxenceC** [comment]
>The downside of setting up all data on the front-end and the volatility of crypto 

True !

>Yup will be addressing this soon

👍

**Comment by djirdehh** [comment]
Resolved!
