### ISSUE TITLE
[ Request ] Clarify License?

### ISSUE THREAD

**Issue by DaveLak** [djirdehh/crypto_vue#19]
Could you clarify which license, if any, the code and assets are released under? Preferably by adding one to the repo?

I ask because I'd like to use the your logo set in a similar project I'm playing around with but only with permission of course.

In any case, awesome app!

**Comment by djirdehh** [comment]
Sincere apologies for the late response.

Everything is under the MIT license so it's free for all :). As a side note; I did manage to get the logo from the Noun Project (I have a paid account :)).
