### ISSUE TITLE
Refresh after clicking on a single crypto doesn't land on the same crypto

### ISSUE THREAD

**Issue by ericbae** [djirdehh/crypto_vue#4]
Awesome app!

But when you click on a single crypto, looks like the route is just "/selected". So if I refresh on that page, the app doesn't know which crypto I clicked on previously. I imagine it would be a relatively simple fix. Great job though, it looks really nice.

**Comment by djirdehh** [comment]
Thanks so much!

Yup you're right. That's a bug I'm going to address. Will aim to direct the user to "/:cryptoCurrency.id" and upon refresh the app should remain intact.

**Comment by odinti** [comment]
Try to use the name of the currency and make it a slug, better for SEO, for saving the link and knowing what it is inmediatly, also take a look for [vue-head](https://github.com/ktquez/vue-head) to improve that idea a little bit further

**Comment by djirdehh** [comment]
@odinti Thanks for pointing that out! Will definitely incorporate that once I get navigation working properly :).

**Comment by djirdehh** [comment]
Pushed a fix in that resolves this. Will close this for now, but will look into using vue-head and improving SEO.
