### ISSUE TITLE
Wrong link to CoinMarketCap in "What's this?"

### ISSUE THREAD

**Issue by lidonis** [djirdehh/crypto_vue#5]
Wrong link to CoinMarketCap in "What's this?"

**Comment by djirdehh** [comment]
Thanks so much for pointing that out. Completely overlooked that :P. I've just pushed the fix to it!

**Comment by lidonis** [comment]
NP. I love the design of your app.

I added another fix because vue router is missing in package.json

Le lun. 31 juil. 2017 à 18:06, Hassan Djirdeh <notifications@github.com> a
écrit :

**Comment by djirdehh** [comment]
Thanks homie! You the best. Will merge that PR in.
