### ISSUE TITLE
The back arrow looks like arrow to switch between currencies

### ISSUE THREAD

**Issue by lidonis** [djirdehh/crypto_vue#7]
The back arrow looks like arrow to switch between currencies. I was confused at first.

**Comment by djirdehh** [comment]
Hm. That's a good point that I didn't think about. I might look into placing the text 'Return' beside it and maybe moving that action to the top left corner.

**Comment by lidonis** [comment]
It's the way to good I think too.
Maybe you cloud also had the functionality to switch between currencies. Or I could do it if you want.

**Comment by djirdehh** [comment]
Hmm. I thought about the functionality between switching currencies but thought that might be overkill to click 10 times to go from beginning to end. How about we resort to just having a more clear return button for now?

**Comment by lidonis** [comment]
Let's go with that :)

**Comment by djirdehh** [comment]
Sounds good :). I'll address this later this evening (or tomorrow).

**Comment by lidonis** [comment]
Our time zones might not be totally in sync

**Comment by djirdehh** [comment]
Yeah that's true lol. I should have said later in the next few hours :P

**Comment by djirdehh** [comment]
Just added the change - a small 'Return' text underneath the arrow so users will know it'll take them back to the main component.

Thanks homie for pointing this out :)
